check dir

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -6,22 +6,18 @@ name: Simple test GH Actions
 on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-    # inputs:
-    #   env:
-    #     required: true
-    #     description: 'Env Type'
-    #     type: choice
-    #     options:
-    #       - npd
-    #       - prd
-    #   instance:
-    #     required: true
-    #     description: 'instance number'
-    #     default: '1'
-
-env:
-  overlay: ci
-  instance: '1'
+    inputs:
+      overlay:
+        required: true
+        description: 'Env Type'
+        type: choice
+        options:
+          - npd
+          - prd
+      instance:
+        required: true
+        description: 'instance number'
+        default: '1'
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -31,7 +27,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: npd
     env:
-      myval: ${{ env.overlay }}-${{ env.instance }}
+      myval: ${{ inputs.overlay }}-${{ inputs.instance }}
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -40,5 +36,11 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run Hello World command
         run: |
-          echo "$myval"
+          echo $myval
+          if [ -d "overlay/$myval" ]; then
+            echo "Success"
+          else
+            echo "Failure"
+            exit 2
+          fi
 
